In [1]:
!conda list numpy

# packages in environment at /Users/mollykings/anaconda3:
#
# Name                    Version                   Build  Channel
numpy                     1.15.4           py36hacdab7b_0  
numpy-base                1.15.4           py36h6575580_0  
numpydoc                  0.8.0                    py36_0  


In [16]:
# We import NumPy into Python
import numpy as np

# We create a 1D ndarray that contains only integers
x = np.array([1, 2, 3, 4, 5])

# Let's print the ndarray we just created using the print() command
print('x = ', x)

x =  [1 2 3 4 5]


In [7]:
x = np.array([1, 2, 3, 4, 5])

print()

print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64


In [8]:
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])
print(Y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
Y.shape

(4, 3)

In [10]:
x = np.array(['Hello','world'])

print()

print('shape:', x.shape)
print('type:', type(x))
print('dtype:', x.dtype)


shape: (2,)
type: <class 'numpy.ndarray'>
dtype: <U5


In [11]:
x = np.array([1,2,'world'])

print()

print('shape:', x.shape)
print('type:', type(x))
print('dtype:', x.dtype)


shape: (3,)
type: <class 'numpy.ndarray'>
dtype: <U21


In [12]:
x = np.array([1,2,2.6])

print()

print('shape:', x.shape)
print('type:', type(x))
print('dtype:', x.dtype)


shape: (3,)
type: <class 'numpy.ndarray'>
dtype: float64


In [14]:
x = np.array([1,2,2.6], dtype=np.int64)

print()

print('shape:', x.shape)
print('type:', type(x))
print('dtype:', x.dtype)


shape: (3,)
type: <class 'numpy.ndarray'>
dtype: int64


In [18]:
x = np.array([1, 2, 3, 4, 5])
np.save('my_array',x)

In [20]:
y = np.load('my_array.npy')
print(y)

[1 2 3 4 5]


In [24]:
x = np.zeros([3,4],dtype=int)
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [25]:
x.dtype

dtype('int64')

In [27]:
x = np.ones([4,5])
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [29]:
x = np.full([4,3],5)
print(x)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [30]:
print(x.dtype)

int64


In [31]:
x = np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [32]:
x = np.diag([10,20,30,50])
print(x)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]


In [37]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]
